on toggle sneak:
    if player is not sneaking:
        stop

    if name of player's tool contains "⟐ Artifact of Poseidon ⟐":

        if {lastSneak_trident::%uuid of player%} is set:
            if difference between now and {lastSneak_trident::%uuid of player%} <= 0.5 seconds:
                delete {lastSneak_trident::%uuid of player%}
                apollotrident(player)
                stop

        set {lastSneak_trident::%uuid of player%} to now
